
sonar.projectKey=smarthome
sonar.projectName=Smarthome Apps Mobile
sonar.sources=lib
sonar.tests=test
sonar.dart.file.suffixes=.dart
sonar.host.url=https://sonarqube-busol.padinet.com/
sonar.token=sqp_6e36882e8fe7f716c81b6c45b9f9c6bd975d61e5
sonar.test.coverage.reportPath=coverage/lcov.info
sonar.flutter.analyzer.mode=flutter